# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Base properties
    minecraft_version=1.20.1
    forge_version=47.4.0
    mapping_channel=parchment
    mapping_version=2023.09.03

# Mod Properties
    mod_version=0.5.7
    maven_group=net.phoenixvine.wiki
    archives_base_name=phoenix_wiki
    mod_id=phoenix_wiki
    mod_name=Phoenix Wiki
    mod_url=
    mod_author=Phoenixvine
    mod_license=LGPLv3.0

emi_version = 1.1.13
